server:
  port: 8081

spring:
  autoconfigure:
    exclude: org.springframework.boot.micrometer.metrics.autoconfigure.system.SystemMetricsAutoConfiguration
  application:
    name: finapp
  datasource:
    url: jdbc:postgresql://localhost:5432/finapp
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    ignore-migration-patterns: "*:missing"

management:
  metrics:
    enable:
      system: false
  endpoints:
    web:
      exposure:
        include: health,info