server:
  port: 8081

spring:
  application:
    name: finapp
  datasource:
    url: jdbc:postgresql://localhost:5432/finapp
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    ignore-migration-patterns: "*:missing"

management:
  endpoints:
    web:
      exposure:
        include: health,info